services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - "5996:8080"  # 将宿主机的 8080 端口映射到容器的 8080 端口
    restart: unless-stopped
    environment:
      - PLANTUML_LIMIT_SIZE=8192