version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue2-markdown-editor
    ports:
      - "30030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - plantuml
    networks:
      - app-network
      
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    restart: unless-stopped
    environment:
      - PLANTUML_LIMIT_SIZE=8192
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 